Update main.yml
if script fails don't fail the entire action, just add a log file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,7 +26,7 @@ jobs:
         run: pip install lxml
 
       - name: Run a one-line script
-        run: python3 ./src/osmnotes_picturebackup.py
+        run: python3 ./src/osmnotes_picturebackup.py || echo "Python script exited with error code $?" >>./log/action_$(date -Imin).halted
       
       # push changes to GITHUB
       - name: push changes
